spring:
  application:
    name: greenpulse-backend
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret: ${JWT_SECRET}

mqtt:
  certificate:
    path: ${MQTT_CERT_PATH}
  private:
    key:
      path: ${MQTT_PRIVATE_KEY_PATH}
  ca:
    path: ${MQTT_CA_PATH}
  endpoint: ${MQTT_ENDPOINT}
  clientId: ${MQTT_CLIENT_ID}
  topic:
    status: ${MQTT_STATUS_TOPIC}
    location: ${MQTT_LOCATION_TOPIC}
  port: ${MQTT_PORT}
